### ISSUE TITLE
In the mingw64 msys2 console, the cef.exe generated by "richardwilkes/cef" cannot be used to generate the browser

### ISSUE THREAD

**Issue by Nihility981** [richardwilkes/cef#11]
Follow the redeme.md operation step by step, the browser cannot be generated.
Even if I use webapp-example's build.sh, it cannot be generated.
![image](https://user-images.githubusercontent.com/19467268/123289953-75c06400-d543-11eb-9544-724e59528192.png)

`
# Setup OS_TYPE
case $(uname -s) in
	Darwin*)  OS_TYPE=darwin ;;
	#Linux*)   OS_TYPE=linux ;;
	MINGW64*) OS_TYPE=windows ;;
	*)        echo "Unsupported OS"; false ;;
esac

# Setup GIT_VERSION
if which git 2>&1 > /dev/null; then
	if [ -z "$(git status --porcelain)" ]; then
		STATE=clean
	else
		STATE=dirty
	fi
	GIT_VERSION=$(git rev-parse HEAD)-$STATE
else
	GIT_VERSION=Unknown
fi

# Ensure the build number is set to something
if [ -z $BUILD_NUMBER ]; then
	BUILD_NUMBER=Unknown
fi

# Setup tools we need
TOOLS_DIR=$PWD/tools
mkdir -p $TOOLS_DIR
export PATH=$TOOLS_DIR:$PATH
go build -o $TOOLS_DIR/cef.exe github.com/richardwilkes/cef
cef.exe install

# Prepare platform-specific distribution bundle
cef.exe dist \
	--bundle "$APP_BUNDLE_NAME" \
	--executable "$APP_NAME" \
	--icon AppIcon.icns \
	--release "$APP_VERSION" \
	--short-release "$APP_VERSION_SHORT" \
	--year "$COPYRIGHT_YEARS" \
	--owner "$COPYRIGHT_OWNER" \
	--id $BUNDLE_ID

case $OS_TYPE in
	darwin)
		touch "dist/macos/$APP_BUNDLE_NAME.app" # Causes Finder to refresh its state
		TARGET_EXE="dist/macos/$APP_BUNDLE_NAME.app/Contents/MacOS/$APP_NAME"
		;;
	windows)
		TARGET_EXE="dist/windows/$APP_NAME.exe"
		;;
	*)
		echo "Unsupported OS"
		false
		;;
esac

go build -o "$TARGET_EXE" -v \
	-ldflags=all="-X github.com/richardwilkes/toolbox/cmdline.AppVersion=$APP_VERSION_SHORT -X github.com/richardwilkes/toolbox/cmdline.GitVersion=$GIT_VERSION -X github.com/richardwilkes/toolbox/cmdline.BuildNumber=$BUILD_NUMBER" \
	./main.go

`
Please help me this is my first time using!

**Comment by richardwilkes** [comment]
Please show what you actually did along with what error occurred.

**Comment by Nihility981** [comment]
Thank you for your reply. Will the build time last for a long time?After I got off work last night, it’s been built now.

**Comment by Nihility981** [comment]
Another problem. The compiled executable file is x64 bit. It can be used on the compiled computer, but it cannot run on other x64 computers.
cef:75.1.4+g4210896+chromium-75.0.3770.100
vc++2015

**Comment by richardwilkes** [comment]
Yes, compiling on Windows is slow, thanks to the really sub-optimal environment on such machines.

I'm afraid I don't understand your last comment. If you can't run it on other machines, you most likely did not copy all of the required shared libraries over to the new machine, or you're running on an incompatible architecture (i.e. 32 bit).

**Comment by Nihility981** [comment]
Yes you are right my colleagues think so too.
I copied the vc++2015 library to the following directory, but still can’t run it.
May I ask which libraries should I install?

**Comment by richardwilkes** [comment]
I'm afraid I no longer have my machine setup to do anything with this project, as the work was abandoned in late 2019 / early 2020 when the project I was doing it for decided to go in a different direction. IIRC, all of the necessary shared libraries were placed in the resulting build tree.
