### ISSUE TITLE
Running "cef install" fails

### ISSUE THREAD

**Issue by D4v1dW3bb** [richardwilkes/cef#12]
Followed the readme. 

When I run `cef install` in the mingw64 console I get:

``Windows is only supported through the use of MINGW64``

What went wrong?

**Comment by richardwilkes** [comment]
I just answered an identical question via email, which may have been you following up. At any rate, for other that may come along and see this, here was my response:

The code checks to verify that you’re running from the MINGW64 console. It does this by looking for the `MSYSTEM` environment variable that the MINGW64 console sets to a value of `MINGW64`. So… either MINGW64 isn’t doing this anymore, or you weren’t issuing the command from that console window.

Unfortunately, the CEF work I did was for a project back in 2019 that was ultimately abandoned, so I’ve not spent any time keeping that repo up to date with changes from upstream (i.e. CEF and MINGW64). In particular, I recall that right towards the end where we decided to go a different direction, the CEF folks had made a change to force the use of the sandbox, which I had not yet looked into and is therefore not supported with this repo’s code.
