### ISSUE TITLE
Build Error on Mac OS: Reason: image not found

### ISSUE THREAD

**Issue by chinyaev** [richardwilkes/cef#2]
Hi!

I install cef on instructional. Downloaded webapp example and try build on Mac, but get error:

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Users/USER/Downloads/*/w.app
  Reason: image not found

Solved with sh build.

**Comment by Chinyaev** [comment]
I try copied Chromium Embedded Framework.framework from cef\Release and now I get different error
[0215/114311.996771:ERROR:icu_util.cc(136)] icudtl.dat not found in bundle
[0215/114311.996885:ERROR:icu_util.cc(172)] Invalid file descriptor to ICU data received.
Trace/BPT trap: 5

And how I can set path to framework?

**Comment by Chinyaev** [comment]
@richardwilkes how solve it? Maybe I'm wrong doing build? I Tried just "go build", "go run", "go build -o test.app"
