### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by lexesv** [richardwilkes/cef#5]
> Currently works for macOS, Windows and Linux.

Hello!
How to use for build in Linux?

Can you give an example?

**Comment by richardwilkes** [comment]
This builds the same on Linux as it does elsewhere. What you won't find, however, is Linux support in my webapp repo that makes use of this library, as I haven't gotten around to that yet... and may never.

**Comment by jannson** [comment]
Support  cross compile in linux for windows ?  something like 
CC=i686-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=386 go build xxx
and we can run the binary in windows, but compile it in linux.
