### ISSUE TITLE
Doesn't compile on MSYS2 / Windows 10

### ISSUE THREAD

**Issue by SylvainGarrigues** [richardwilkes/cef#7]
`C:\Users\Sylvain\go\pkg\mod\github.com\richardwilkes\cef@v0.5.2\cef\functions_gen.go:336:49: too many arguments in call to _Cfunc_cef_label_button_create
        have (*_Ctype_struct__cef_button_delegate_t, *_Ctype_struct__cef_string_utf16_t, _Ctype_int)
        want (*_Ctype_struct__cef_button_delegate_t, *_Ctype_struct__cef_string_utf16_t)
C:\Users\Sylvain\go\pkg\mod\github.com\richardwilkes\cef@v0.5.2\cef\functions_gen.go:363:47: too many arguments in call to _Cfunc_cef_menu_button_create
        have (*_Ctype_struct__cef_menu_button_delegate_t, *_Ctype_struct__cef_string_utf16_t, _Ctype_int)
        want (*_Ctype_struct__cef_menu_button_delegate_t, *_Ctype_struct__cef_string_utf16_t)
`

**Comment by richardwilkes** [comment]
This is usually caused by not having the correct version of the CEF headers and libraries installed prior to trying to build the software. If the install has been corrupted, you might want to try `cef install --force` to force a fresh install.
