### ISSUE TITLE
ResourceHandler.ProcessRequest

### ISSUE THREAD

**Issue by dongchaoforever** [richardwilkes/cef#8]
I defined a custom class that implements the ResourceHandler interface, and while processing the ProcessRequest method, the program crash after the callback.Cont() method is called. The tracking found that the error is Proxy not found for ID, may I ask how I should register a CallBack
Thank You.  merry christmas

**Comment by richardwilkes** [comment]
It sounds like you either did not call `cef.NewResourceHandler()` with your proxy to create the `ResourceHandler` or that you freed the resulting `ResourceHandler` before the callback came in.

**Comment by dongchaoforever** [comment]
Can you give me an example of how to load a local HTML file

**Comment by richardwilkes** [comment]
I have had no need for that, so haven't tried yet. There is probably some sort of security manager you have to set in order to allow access to the local hard drive. I'd suggest reading whatever docs the CEF folks have regarding this or asking the question in their forums.
